services:
  app:
    build: .
    restart: unless-stopped
    volumes:
      - ./:/var/www
    depends_on:
       database:
          condition: service_healthy

  webserver:
    image: nginx:1.17.1-alpine
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app

  database:
    image: mysql:9.4.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "${DATABASE_USER}", "-p${DATABASE_PASSWORD}" ]
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  db_data:
